name: omva
run-name: ${{ github.actor }} is deploying the web

on:
  push:
    tags:
      - 'v*.*.*'

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel
        timeout-minutes: 10
        run: vercel deploy --prod --token=$VERCEL_TOKEN --yes
